part of 'spark_joy_create_report_screen.dart';

class _SparkJoyMediaTagRegistry {
  const _SparkJoyMediaTagRegistry._();

  static const Set<String> interiorDashboardElementIds = {
    'dashboard_top',
    'instrument_cluster',
    'center_display',
    'climate_panel',
    'center_console',
    'gear_selector_area',
    'dashboard_buttons_left',
  };

  static const Map<String, List<_MediaOption>> mediaElementOptionsByGroup = {
    'body': [
      _MediaOption(id: 'hood', label: 'Капот'),
      _MediaOption(id: 'front_bumper', label: 'Передний бампер'),
      _MediaOption(id: 'roof', label: 'Крыша'),
      _MediaOption(id: 'trunk', label: 'Багажник'),
      _MediaOption(id: 'rear_bumper', label: 'Задний бампер'),
      _MediaOption(id: 'left_front_fender', label: 'Левое переднее крыло'),
      _MediaOption(id: 'left_front_door', label: 'Левая передняя дверь'),
      _MediaOption(id: 'left_rear_door', label: 'Левая задняя дверь'),
      _MediaOption(id: 'left_rear_fender', label: 'Левое заднее крыло'),
      _MediaOption(id: 'right_front_fender', label: 'Правое переднее крыло'),
      _MediaOption(id: 'right_front_door', label: 'Правая передняя дверь'),
      _MediaOption(id: 'right_rear_door', label: 'Правая задняя дверь'),
      _MediaOption(id: 'right_rear_fender', label: 'Правое заднее крыло'),
      _MediaOption(
        id: 'uh_body_elements',
        label: 'Кузовные элементы под капотом',
      ),
      _MediaOption(
        id: 'inner_trunk_lid',
        label: 'Внутренняя сторона крышки багажника',
      ),
      _MediaOption(id: 'body_general', label: 'Общее состояние'),
    ],
    'structural': [
      _MediaOption(id: 'a_pillar_left', label: 'Передняя стойка левая (A)'),
      _MediaOption(id: 'a_pillar_right', label: 'Передняя стойка правая (A)'),
      _MediaOption(id: 'b_pillar_left', label: 'Центральная стойка левая (B)'),
      _MediaOption(
        id: 'b_pillar_right',
        label: 'Центральная стойка правая (B)',
      ),
      _MediaOption(id: 'c_pillar_left', label: 'Задняя стойка левая (C)'),
      _MediaOption(id: 'c_pillar_right', label: 'Задняя стойка правая (C)'),
      _MediaOption(id: 'rail_left', label: 'Лонжерон левый'),
      _MediaOption(id: 'rail_right', label: 'Лонжерон правый'),
      _MediaOption(id: 'sill_left', label: 'Порог левый'),
      _MediaOption(id: 'sill_right', label: 'Порог правый'),
      _MediaOption(
        id: 'fender_liner_left_front',
        label: 'Брызговик левый передний',
      ),
      _MediaOption(
        id: 'fender_liner_right_front',
        label: 'Брызговик правый передний',
      ),
      _MediaOption(
        id: 'fender_liner_left_rear',
        label: 'Брызговик левый задний',
      ),
      _MediaOption(
        id: 'fender_liner_right_rear',
        label: 'Брызговик правый задний',
      ),
      _MediaOption(id: 'structural_general', label: 'Общее состояние'),
    ],
    'glass': [
      _MediaOption(id: 'windshield', label: 'Лобовое стекло'),
      _MediaOption(id: 'rear_glass', label: 'Заднее стекло'),
      _MediaOption(id: 'glass_front_left', label: 'Переднее левое стекло'),
      _MediaOption(id: 'glass_front_right', label: 'Переднее правое стекло'),
      _MediaOption(id: 'glass_rear_left', label: 'Заднее левое стекло'),
      _MediaOption(id: 'glass_rear_right', label: 'Заднее правое стекло'),
      _MediaOption(id: 'mirror_left', label: 'Зеркало левое'),
      _MediaOption(id: 'mirror_right', label: 'Зеркало правое'),
      _MediaOption(id: 'glass_general', label: 'Общее состояние'),
    ],
    'lighting': [
      _MediaOption(id: 'headlights_front', label: 'Передние фары'),
      _MediaOption(id: 'taillights_rear', label: 'Задние фонари'),
      _MediaOption(id: 'drl', label: 'ДХО'),
      _MediaOption(id: 'fog_lights', label: 'Противотуманки'),
      _MediaOption(id: 'turn_signals', label: 'Поворотники'),
      _MediaOption(id: 'brake_lights', label: 'Стоп-сигналы'),
      _MediaOption(id: 'plate_light', label: 'Подсветка номера'),
      _MediaOption(id: 'lighting_general', label: 'Общее состояние'),
    ],
    'underhood': [
      _MediaOption(id: 'uh_engine', label: 'Двигатель'),
      _MediaOption(id: 'uh_accessories', label: 'Навесное оборудование'),
      _MediaOption(id: 'uh_cooling', label: 'Система охлаждения'),
      _MediaOption(id: 'uh_fuel', label: 'Топливная система'),
      _MediaOption(id: 'uh_intake_turbo', label: 'Впуск / турбина'),
      _MediaOption(id: 'uh_exhaust_ecology', label: 'Выпуск / экология'),
      _MediaOption(id: 'uh_electrical', label: 'Электрика'),
      _MediaOption(id: 'uh_brakes', label: 'Тормозная система'),
      _MediaOption(id: 'uh_steering', label: 'Рулевое управление'),
      _MediaOption(id: 'uh_fluids', label: 'Жидкости и бачки'),
      _MediaOption(id: 'uh_general', label: 'Общее состояние'),
    ],
    'wheels': [
      _MediaOption(id: 'front_left_wheel', label: 'Переднее левое колесо'),
      _MediaOption(id: 'front_right_wheel', label: 'Переднее правое колесо'),
      _MediaOption(id: 'rear_left_wheel', label: 'Заднее левое колесо'),
      _MediaOption(id: 'rear_right_wheel', label: 'Заднее правое колесо'),
      _MediaOption(id: 'spare_wheel', label: 'Запасное колесо / докатка'),
      _MediaOption(
        id: 'front_left_brake',
        label: 'Передний левый тормозной механизм',
      ),
      _MediaOption(
        id: 'front_right_brake',
        label: 'Передний правый тормозной механизм',
      ),
      _MediaOption(
        id: 'rear_left_brake',
        label: 'Задний левый тормозной механизм',
      ),
      _MediaOption(
        id: 'rear_right_brake',
        label: 'Задний правый тормозной механизм',
      ),
      _MediaOption(id: 'wheels_general', label: 'Общее состояние'),
    ],
    'interior': [
      _MediaOption(id: 'front_seats', label: 'Передние сиденья'),
      _MediaOption(id: 'rear_seats', label: 'Задние сиденья'),
      _MediaOption(id: 'door_cards', label: 'Дверные карты'),
      _MediaOption(id: 'headliner', label: 'Потолок'),
      _MediaOption(id: 'trunk_interior', label: 'Багажное отделение'),
      _MediaOption(id: 'steering_wheel', label: 'Рулевое колесо'),
      _MediaOption(id: 'dashboard_top', label: 'Торпедо'),
      _MediaOption(id: 'instrument_cluster', label: 'Комбинация приборов'),
      _MediaOption(id: 'center_display', label: 'Центральный экран'),
      _MediaOption(id: 'climate_panel', label: 'Блок климата'),
      _MediaOption(id: 'center_console', label: 'Центральная консоль'),
      _MediaOption(id: 'gear_selector_area', label: 'Зона селектора КПП'),
      _MediaOption(id: 'dashboard_buttons_left', label: 'Кнопки слева от руля'),
      _MediaOption(id: 'interior_general', label: 'Общее состояние'),
    ],
    'diagnostics': [
      _MediaOption(id: 'diag_engine', label: 'Двигатель'),
      _MediaOption(id: 'diag_transmission', label: 'Трансмиссия / АКПП / КПП'),
      _MediaOption(id: 'diag_abs_esp', label: 'ABS / ESP / тормозные системы'),
      _MediaOption(id: 'diag_srs_airbag', label: 'SRS / Airbag / подушки'),
      _MediaOption(id: 'diag_electric', label: 'Электрика / бортовая сеть'),
      _MediaOption(
        id: 'diag_ecology',
        label: 'Экология / катализатор / EGR / лямбда',
      ),
      _MediaOption(
        id: 'diag_body_comfort',
        label: 'Кузовная электроника / комфорт',
      ),
      _MediaOption(
        id: 'diag_steering_suspension',
        label: 'Рулевое управление / подвеска',
      ),
      _MediaOption(id: 'diag_awd', label: 'Полный привод / AWD / 4WD'),
      _MediaOption(id: 'diag_climate', label: 'Климат / кондиционер'),
      _MediaOption(id: 'diag_immobilizer', label: 'Иммобилайзер / запуск'),
      _MediaOption(id: 'diag_general', label: 'Общее состояние'),
    ],
  };

  static const Map<String, List<String>> mediaTagOptionsByGroup = {
    'body': [
      'Полный окрас',
      'Окрас большей части',
      'Глубокая деформация',
      'Шпатлёвка от 400мкм',
      'Царапина от 10см',
      'Замена элемента',
      'Царапина до 5 см',
      'Царапина до 10 см',
      'Шпатлёвка до 400мкм',
      'Частичный окрас 1/4',
      'Вмятина без повр. ЛКП',
      'Скол',
    ],
    'glass': [
      'Трещина',
      'Замена (не оригинал)',
      'Расслоение',
      'Скол',
      'Царапина',
      'Тонировка',
      'Повреждение уплотнителя',
      'Запотевание / влага',
    ],
    'structural': [
      'Деформация',
      'Трещина',
      'Коррозия',
      'Замена элемента',
      'Следы сварки',
      'Нештатный герметик',
      'Подкрас / шпатлёвка',
    ],
    'lighting': [
      'Не работает',
      'Трещина / разрушение',
      'Не оригинал',
      'Помутнение',
      'Запотевание / влага',
      'Царапина',
      'Скол',
    ],
    'underhood': [
      'Течь / подтёк',
      'Механическое повреждение',
      'Не оригинал',
      'Коррозия',
      'Сильное загрязнение',
      'Нештатная проводка',
    ],
    'wheels': [
      'Повреждение шины',
      'Повреждение диска',
      'Люфт ступицы',
      'Неравномерный износ',
      'Коррозия диска',
      'Износ тормозов',
      'Скрип / биение',
    ],
    'interior': [
      'Разрыв обивки',
      'Прожог',
      'Трещина элемента',
      'Сломанный элемент',
      'Не работает функция',
      'Износ',
      'Потёртость',
      'Царапины',
      'Пятна',
      'Повреждение обшивки',
      'Посторонний запах',
    ],
    'interior_dashboard': [
      'Трещина панели',
      'Экран не работает',
      'Приборная панель неисправна',
      'Блок климата неисправен',
      'Кнопки не работают',
      'Нештатная установка',
      'Царапины',
      'Потёртость',
      'Битые пиксели / засветы',
      'Неисправна подсветка',
      'Следы разбора',
      'Стёрты пиктограммы',
    ],
    'diagnostics': [
      'Ошибка двигателя',
      'Ошибка АКПП/КПП',
      'Ошибка подушек безопасности',
      'Ошибка ABS/ESP',
      'Ошибка электрики',
      'Ошибка экологии/катализатора',
      'Ошибка кузовных систем',
      'Замороженная ошибка',
      'Предупреждение двигателя',
      'Предупреждение АКПП/КПП',
      'Предупреждение ABS/ESP',
      'Предупреждение электрики',
      'Предупреждение кузовных систем',
    ],
  };

  static const Map<String, Set<String>> mediaSeriousTagsByGroup = {
    'body': {
      'Полный окрас',
      'Окрас большей части',
      'Глубокая деформация',
      'Шпатлёвка от 400мкм',
      'Царапина от 10см',
      'Замена элемента',
    },
    'glass': {'Трещина', 'Замена (не оригинал)', 'Расслоение'},
    'structural': {'Деформация', 'Трещина', 'Коррозия', 'Замена элемента'},
    'lighting': {'Не работает', 'Трещина / разрушение', 'Не оригинал'},
    'underhood': {'Течь / подтёк', 'Механическое повреждение', 'Не оригинал'},
    'wheels': {'Повреждение шины', 'Повреждение диска', 'Люфт ступицы'},
    'interior': {
      'Разрыв обивки',
      'Прожог',
      'Трещина элемента',
      'Сломанный элемент',
      'Не работает функция',
    },
    'interior_dashboard': {
      'Трещина панели',
      'Экран не работает',
      'Приборная панель неисправна',
      'Блок климата неисправен',
      'Кнопки не работают',
      'Нештатная установка',
    },
    'diagnostics': {
      'Ошибка двигателя',
      'Ошибка АКПП/КПП',
      'Ошибка подушек безопасности',
      'Ошибка ABS/ESP',
      'Ошибка электрики',
      'Ошибка экологии/катализатора',
      'Ошибка кузовных систем',
    },
  };

  static const Map<String, List<String>> diagnosticTagOptionsByElement = {
    'diag_engine': [
      'Ошибки двигателя',
      'Пропуски зажигания',
      'Ошибка датчика',
      'Неровная работа',
      'Ошибка по смеси',
      'Низкое давление топлива',
      'Ошибка турбины',
      'Передув',
      'Недодув',
      'Ошибка фаз',
      'Ошибка ГРМ',
      'Предупреждение по двигателю',
      'Нестабильная работа',
      'Подозрение на пропуски',
      'Ошибка по датчику',
      'Требуется проверка топливной системы',
      'Требуется проверка наддува',
      'Подозрение на подсос воздуха',
    ],
    'diag_transmission': [
      'Ошибки АКПП',
      'Аварийный режим АКПП',
      'Пробуксовка',
      'Ошибка мехатроника',
      'Ошибка сцепления',
      'Ошибка DSG',
      'Ошибка вариатора',
      'Предупреждение по АКПП',
      'Требуется проверка АКПП',
      'Есть замечания по переключениям',
      'Подозрение на износ сцепления',
      'Рекомендована диагностика трансмиссии',
    ],
    'diag_abs_esp': [
      'Ошибка ABS',
      'Ошибка ESP',
      'Ошибка датчика колеса',
      'Ошибка EPB',
      'Неисправность тормозной системы',
      'Предупреждение ABS/ESP',
      'Требуется проверка датчика колеса',
      'Требуется проверка тормозной системы',
    ],
    'diag_srs_airbag': [
      'Ошибка SRS',
      'Ошибка Airbag',
      'Неисправность подушек безопасности',
      'Ошибка преднатяжителей',
      'Ошибка датчика удара',
      'Предупреждение SRS',
      'Требуется проверка системы безопасности',
    ],
    'diag_electric': [
      'Ошибка электрики',
      'Низкое напряжение',
      'Ошибка генератора',
      'Короткое замыкание',
      'Обрыв цепи',
      'Ошибка CAN',
      'Потеря связи',
      'Ошибка блока управления',
      'Предупреждение по электрике',
      'Нестабильное питание',
      'Требуется проверка аккумулятора',
      'Требуется проверка генератора',
      'Периодическая потеря связи',
    ],
    'diag_ecology': [
      'Ошибка катализатора',
      'Ошибка лямбда-зонда',
      'Ошибка EGR',
      'Ошибка DPF',
      'Ошибка AdBlue',
      'Предупреждение по экологии',
      'Требуется проверка катализатора',
      'Требуется проверка лямбда-зонда',
      'Рекомендована проверка DPF',
    ],
    'diag_body_comfort': [
      'Ошибка системы',
      'Неисправность',
      'Требуется проверка',
      'Есть замечания',
    ],
    'diag_steering_suspension': [
      'Ошибка системы',
      'Неисправность',
      'Требуется проверка',
      'Есть замечания',
    ],
    'diag_awd': [
      'Ошибка системы',
      'Неисправность',
      'Требуется проверка',
      'Есть замечания',
    ],
    'diag_climate': [
      'Ошибка системы',
      'Неисправность',
      'Требуется проверка',
      'Есть замечания',
    ],
    'diag_immobilizer': [
      'Ошибка системы',
      'Неисправность',
      'Требуется проверка',
      'Есть замечания',
    ],
  };

  static const Map<String, Set<String>> diagnosticSeriousTagsByElement = {
    'diag_engine': {
      'Ошибки двигателя',
      'Пропуски зажигания',
      'Ошибка датчика',
      'Неровная работа',
      'Ошибка по смеси',
      'Низкое давление топлива',
      'Ошибка турбины',
      'Передув',
      'Недодув',
      'Ошибка фаз',
      'Ошибка ГРМ',
    },
    'diag_transmission': {
      'Ошибки АКПП',
      'Аварийный режим АКПП',
      'Пробуксовка',
      'Ошибка мехатроника',
      'Ошибка сцепления',
      'Ошибка DSG',
      'Ошибка вариатора',
    },
    'diag_abs_esp': {
      'Ошибка ABS',
      'Ошибка ESP',
      'Ошибка датчика колеса',
      'Ошибка EPB',
      'Неисправность тормозной системы',
    },
    'diag_srs_airbag': {
      'Ошибка SRS',
      'Ошибка Airbag',
      'Неисправность подушек безопасности',
      'Ошибка преднатяжителей',
      'Ошибка датчика удара',
    },
    'diag_electric': {
      'Ошибка электрики',
      'Низкое напряжение',
      'Ошибка генератора',
      'Короткое замыкание',
      'Обрыв цепи',
      'Ошибка CAN',
      'Потеря связи',
      'Ошибка блока управления',
    },
    'diag_ecology': {
      'Ошибка катализатора',
      'Ошибка лямбда-зонда',
      'Ошибка EGR',
      'Ошибка DPF',
      'Ошибка AdBlue',
    },
    'diag_body_comfort': {'Ошибка системы', 'Неисправность'},
    'diag_steering_suspension': {'Ошибка системы', 'Неисправность'},
    'diag_awd': {'Ошибка системы', 'Неисправность'},
    'diag_climate': {'Ошибка системы', 'Неисправность'},
    'diag_immobilizer': {'Ошибка системы', 'Неисправность'},
  };
}
